CREATE TABLE "Component" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "repository" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Repository" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "EnvDiscovery" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "component" TEXT NOT NULL,
  "varsJson" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "EnvMapping" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "discoveryId" TEXT NOT NULL,
  "mappingJson" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "RecipeIndex" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "title" TEXT NOT NULL,
  "version" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "ResourceState" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "recipeId" TEXT NOT NULL,
  "stateJson" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "SandboxSession" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "component" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Execution" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "componentId" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "durationMs" INTEGER,
  "memoryMb" INTEGER,
  "artifactRef" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
